# NumPy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## NumPy Arrays(ndarray)

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
matrix[0]

array([1, 2, 3])

In [10]:
matrix[0][0]

1

In [8]:
type(matrix[0][0])

numpy.int64

In [19]:
ndarray = np.array([1,2,3],dtype=np.uint8) #unsigned integer8(0-255)

In [20]:
ndarray

array([1, 2, 3], dtype=uint8)

In [17]:
ndarray2 = np.array([1,2,3],dtype=np.float32) #unsigned float32

In [18]:
ndarray2

array([1., 2., 3.], dtype=float32)

## ndarrayの演算

In [22]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [26]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
#listは演算できない
a = [1,2,3]
b = [1,2,3]

In [30]:
a + b

[1, 2, 3, 1, 2, 3]

In [38]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3 = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [39]:
array1

array([1, 2, 3])

In [40]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [41]:
array3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [42]:
array2 + array3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

array1 + array2 = array2 + array3

broadcastingという

## Shape

In [44]:
array1 = np.array([1,2])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
#shapeが違うからbroadcastingできない
array1 + array2

ValueError: operands could not be broadcast together with shapes (2,) (3,3) 

In [48]:
ndarray = np.array([[1,2],[3,4],[5,6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
ndarray.shape

(3, 2)

In [50]:
ndarray.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
ndarray.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [52]:
ndarray1 = np.array([1,2,3])
ndarray2 = np.array([[1,2,3]])

In [53]:
ndarray1.shape

(3,)

In [54]:
ndarray2.shape

(1, 3)

In [58]:
#次元追加
np.expand_dims(ndarray1,axis=0)

array([[1, 2, 3]])

In [59]:
np.expand_dims(ndarray1,axis=1)

array([[1],
       [2],
       [3]])

In [60]:
#次元削減
np.squeeze(ndarray2)

array([1, 2, 3])

In [63]:
#1次元化
ndarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## IndexingとSlicing

In [65]:
ndarray = np.array([1,2,3,4])

In [66]:
ndarray

array([1, 2, 3, 4])

In [68]:
ndarray[-1]

4

In [69]:
ndarray = np.array([[1,2],[3,4],[5,6]])

In [70]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
ndarray[0]

array([1, 2])

In [72]:
ndarray[0][1]

2

In [74]:
#こちらの方が一般的だし簡単
ndarray[0,1]

2

In [76]:
ndarray = np.array([1,2,3,4])
ndarray

array([1, 2, 3, 4])

In [78]:
ndarray[1:3]
#N以上M未満

array([2, 3])

In [79]:
ndarray[:3]

array([1, 2, 3])

In [80]:
ndarray[1:]

array([2, 3, 4])

In [81]:
ndarray[-2:]

array([3, 4])

In [82]:
ndarray[:-2]

array([1, 2])

In [83]:
ndarray[:]

array([1, 2, 3, 4])

In [84]:
ndarray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [86]:
ndarray[:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## arrayを関数で作成(arange, linspace, logspace)

In [92]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
np.arange(3,15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
np.arange(4,15,3)

array([ 4,  7, 10, 13])

In [94]:
list(range(2,14,2))

[2, 4, 6, 8, 10, 12]

In [98]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [103]:
np.logspace(0,3,10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

In [104]:
np.linspace(0,3,10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [107]:
10 ** 0.33333333

2.1544346734959863

## 行列生成

In [112]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
np.zeros(3)

array([0., 0., 0.])

In [114]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [115]:
np.ones(3)

array([1., 1., 1.])

In [117]:
np.ones([4,3])+5

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [119]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.randomを使って乱数生成

In [124]:
## 疑似乱数 pseudo
np.random.rand()

0.7000274628812297

In [125]:
np.random.rand(3,4)

array([[0.0125999 , 0.39847134, 0.96318216, 0.12338458],
       [0.61045565, 0.49211415, 0.8677658 , 0.13581731],
       [0.26980105, 0.95007567, 0.66680636, 0.15204369]])

### seedの設定

In [139]:
np.random.seed(1)

In [140]:
np.random.rand()

0.417022004702574

### 標準正規分布 np.random.randn

In [145]:
np.random.randn()

-2.363468604780012

In [148]:
np.random.randn(3,3)

array([[-0.77229442, -0.09387704, -0.16977402],
       [-0.54114463,  0.53794761,  0.39128265],
       [ 2.21191487, -0.16224463,  0.29117816]])

In [151]:
np.random.normal(3,3,10)

array([2.00302546, 5.33143956, 3.27105354, 2.44020758, 5.22977571,
       1.7424658 , 3.01488137, 0.4993282 , 1.86192333, 1.36913253])

In [152]:
np.random.randint(10,100,[3,3])

array([[36, 94, 40],
       [74, 32, 62],
       [13, 80, 22]])

In [158]:
np.random.choice([1,2,3,4,5,6])

6

In [160]:
np.random.choice(np.arange(0,10,2))

4

## 統計量

In [162]:
std_norm = np.random.randn(5,5)

In [163]:
std_norm

array([[ 1.08361763, -0.70616919, -0.79133379, -0.38226546,  0.52532008],
       [ 0.18555184,  1.33191523,  0.36782973, -1.27829505, -0.12360893],
       [-0.55336186,  1.04765435,  0.21922434, -0.69195694,  0.80723265],
       [-0.38842842, -1.36583202,  1.31945877, -1.00541669, -0.45965174],
       [ 0.21347445, -0.2361257 , -1.70671527, -1.27771126, -0.68947875]])

In [164]:
std_norm.max()

1.3319152261593887

In [165]:
np.max(std_norm)

1.3319152261593887

In [166]:
std_norm.min()

-1.7067152650332458

In [168]:
# 最大値のindexを取得
std_norm.argmax()

6

In [172]:
std_norm.flatten()[6]

1.3319152261593887

In [174]:
#平均
std_norm.mean()

-0.18220287986151326

In [176]:
#中央値
np.median(std_norm)

-0.38226546314295734

In [177]:
# 中央値 vs 平均値

In [182]:
a = np.random.randn(1000,1000)
import time

In [184]:
before = time.time()
np.median(a)
after = time.time()
print(after - before)

0.024328947067260742


In [185]:
after_median = time.time()
np.mean(a)
after_mean = time.time()
print(after_mean - after_median)

0.0029256343841552734


In [186]:
#標準偏差を取得

In [187]:
np.std(std_norm)

0.8524832300645266

## 数学で使える関数

In [194]:
#平方根
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [192]:
x = np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [195]:
#log
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [198]:
#指数関数
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [200]:
# ネイピア数
np.e

2.718281828459045

In [204]:
array = np.arange(1,11)
np.sum([1,2,3])

6

In [205]:
np.sum(array)

55

In [206]:
ndarray = array.reshape(2,5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [208]:
np.sum(ndarray,axis=1)

array([15, 40])

In [210]:
array = np.arange(-10,0)
array

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [213]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## NaNの扱い

In [214]:
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

In [215]:
type(np.nan)

float

In [216]:
a = None
a is None

True

In [218]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

## np.clip()

In [220]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
np.clip(array,3,8)

array([3, 3, 3, 3, 4, 5, 6, 7, 8, 8])

In [224]:
## numpy arrayのcondition

In [225]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.where

In [228]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [231]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [232]:
ndarray = array.reshape(2,5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [233]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [235]:
(ndarray > 3).all()

False

In [236]:
(ndarray > 3).any()

True

In [237]:
(ndarray > 3).all(axis=1)

array([False,  True])

### np.unique()

In [240]:
array = np.array([1,1,2,3,4,4,5,6,6,6,])
array

array([1, 1, 2, 3, 4, 4, 5, 6, 6, 6])

In [241]:
np.unique(array)

array([1, 2, 3, 4, 5, 6])

In [242]:
np.unique(array,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 1, 1, 2, 1, 3]))

### np.bincount()

In [243]:
np.bincount(array)

array([0, 2, 1, 1, 2, 1, 3])

### np.concatenate

In [246]:
ndarray_even = np.arange(0,18,2).reshape(3,3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [247]:
ndarray_odd = np.arange(1,19,2).reshape(3,3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [249]:
np.concatenate([ndarray_even,ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [251]:
np.concatenate([ndarray_even,ndarray_odd],axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [252]:
np.stack([ndarray_even,ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [253]:
np.stack([ndarray_even,ndarray_odd]).shape

(2, 3, 3)

### np.transpose.T

In [255]:
ndarray = np.random.randn(3,4)
ndarray

array([[-0.50709335,  0.02656985, -2.40949448,  0.66281594],
       [ 0.07942682,  0.9551467 , -0.64495102,  0.00843896],
       [-1.64351594, -0.11451383,  0.07033991, -0.01761356]])

In [257]:
ndarray.shape

(3, 4)

In [258]:
np.transpose(ndarray)

array([[-0.50709335,  0.07942682, -1.64351594],
       [ 0.02656985,  0.9551467 , -0.11451383],
       [-2.40949448, -0.64495102,  0.07033991],
       [ 0.66281594,  0.00843896, -0.01761356]])

In [259]:
np.transpose(ndarray).shape

(4, 3)

In [260]:
ndarray.T

array([[-0.50709335,  0.07942682, -1.64351594],
       [ 0.02656985,  0.9551467 , -0.11451383],
       [-2.40949448, -0.64495102,  0.07033991],
       [ 0.66281594,  0.00843896, -0.01761356]])

## np.save('path',array) np.load('path')

In [261]:
ndarray = np.random.randn(3,4,5)
ndarray

array([[[-0.68611732, -0.21157573,  0.15359917, -0.08316086,
         -1.95658945],
        [-0.13402762, -1.58583372, -0.28478678, -0.65945482,
         -0.84717992],
        [ 2.16192678,  0.15979793, -0.02909325,  0.58400243,
         -0.67491871],
        [ 0.72477659,  0.01074087, -0.38912979,  0.9678782 ,
          1.64065203]],

       [[ 0.55696369,  0.23258294,  0.53911289, -1.56140499,
         -0.28531342],
        [ 1.41779893, -0.29861525,  0.80273275,  0.76733967,
         -0.58528946],
        [-1.41633891,  1.26421347,  0.03020866, -0.33938697,
          0.30622708],
        [-0.37046748, -1.17128076, -0.55135924, -0.08778326,
         -0.4770715 ]],

       [[ 0.42361808, -1.30538629, -0.17670431,  0.14943106,
         -1.09004919],
        [ 1.29691452,  0.41330816,  2.05575356, -0.18090493,
          1.05758274],
        [-1.01045891, -0.34208806,  0.75675618, -0.84613321,
         -0.4203599 ],
        [ 0.8852637 , -0.48374317, -0.9311744 , -0.5594131 ,
          0

In [263]:
np.save('sample_ndarray',ndarray)

In [264]:
loaded_ndarray = np.load('sample_ndarray.npy')

In [265]:
loaded_ndarray

array([[[-0.68611732, -0.21157573,  0.15359917, -0.08316086,
         -1.95658945],
        [-0.13402762, -1.58583372, -0.28478678, -0.65945482,
         -0.84717992],
        [ 2.16192678,  0.15979793, -0.02909325,  0.58400243,
         -0.67491871],
        [ 0.72477659,  0.01074087, -0.38912979,  0.9678782 ,
          1.64065203]],

       [[ 0.55696369,  0.23258294,  0.53911289, -1.56140499,
         -0.28531342],
        [ 1.41779893, -0.29861525,  0.80273275,  0.76733967,
         -0.58528946],
        [-1.41633891,  1.26421347,  0.03020866, -0.33938697,
          0.30622708],
        [-0.37046748, -1.17128076, -0.55135924, -0.08778326,
         -0.4770715 ]],

       [[ 0.42361808, -1.30538629, -0.17670431,  0.14943106,
         -1.09004919],
        [ 1.29691452,  0.41330816,  2.05575356, -0.18090493,
          1.05758274],
        [-1.01045891, -0.34208806,  0.75675618, -0.84613321,
         -0.4203599 ],
        [ 0.8852637 , -0.48374317, -0.9311744 , -0.5594131 ,
          0

In [266]:
dictionary = {
    'id':123456,
    'image':ndarray
}

In [267]:
np.save('sample_dict',dictionary)

In [268]:
loaded_dictionary = np.load('sample_dict.npy')

ValueError: Object arrays cannot be loaded when allow_pickle=False

In [269]:
loaded_dictionary = np.load('sample_dict.npy',allow_pickle=True)

In [270]:
loaded_dictionary

array({'id': 123456, 'image': array([[[-0.68611732, -0.21157573,  0.15359917, -0.08316086,
         -1.95658945],
        [-0.13402762, -1.58583372, -0.28478678, -0.65945482,
         -0.84717992],
        [ 2.16192678,  0.15979793, -0.02909325,  0.58400243,
         -0.67491871],
        [ 0.72477659,  0.01074087, -0.38912979,  0.9678782 ,
          1.64065203]],

       [[ 0.55696369,  0.23258294,  0.53911289, -1.56140499,
         -0.28531342],
        [ 1.41779893, -0.29861525,  0.80273275,  0.76733967,
         -0.58528946],
        [-1.41633891,  1.26421347,  0.03020866, -0.33938697,
          0.30622708],
        [-0.37046748, -1.17128076, -0.55135924, -0.08778326,
         -0.4770715 ]],

       [[ 0.42361808, -1.30538629, -0.17670431,  0.14943106,
         -1.09004919],
        [ 1.29691452,  0.41330816,  2.05575356, -0.18090493,
          1.05758274],
        [-1.01045891, -0.34208806,  0.75675618, -0.84613321,
         -0.4203599 ],
        [ 0.8852637 , -0.48374317, -0.9311